= Kubernetes Chatbot

This repository contains the code for creating a Kubernetes chatbot using Amazon Lex.

The users can interact with this chatbot using the following means:

. Text (Slack)

Other possible integrations are:

. Text (Phone/SMS, Facebook Messenger)
. Voice (Alexa, Phone/Call)

== Slack

. Get yourself invited to the team: <ADD LINK>
. DM with the user `k8s_chatbot`
. Create cluster using the following commands:

    create a 3 master 3 worker cluster in us-west-1

Here is a sample communication:

<ADD IMAGE>

This bot can be integrated with your own Slack team by following the instructions ADD LINK.

== Issues

. How can kubectl configuration be obtained? Currently kops updates local `kubeconfig` and has no intuititive way to return the configuration information.
. How would Slack authenticate with AWS and pass the credentials to chatbot?
. Allow instance size to be specified in the intent
. Voice integration
.. How would AWS authentication work
.. How would the API server URI be returned
.. How would a cryptic cluster name be returned
.. User may ask to return details via an email/SMS/slack
. How can kops scale an existing cluster
. Add a new intent to upgrade a cluster


